#include <fstream>

using namespace std;
ifstream in ("cuart.in");
ofstream out("cuart.out");
int main()
{
    int n,p,g,m,nrg,nrm,cg,put=1,max=0,s,t,elemg=0,elemm=0,sm,st,nrcg=0,nrcm=0,cm,cnt=0,i;
    in>>p>>n;
    for(i=1; i<=n; i++)
    {
        in>>g;
        cg=g;
        put=1;
        nrg=0;
        while(cg)
        {
            if(cg%2!=0)
            {
                nrg=nrg+cg%10*put;
                put*=10;
            }
            cg/=10;
        }
        if(nrg==0)
        {
            if(max<g)
                max=g;
        }
        else
        {
            t=1;
            s=0;
            while(s+t<=nrg)
            {
                s+=t;
                t+=4;
            }
            if(s==nrg)
            {
                nrcg++;
            }
            if(cnt==0)
            {
                elemg=nrg;
                cnt=1;
            }
        }
    }
    cnt=0;
    for(i=1; i<=n; i++)
    {
        in>>m;
        cm=m;
        put=1;
        nrm=0;
        while(cm)
        {
            if(cm%2==0)
            {
                nrm=nrm+cm%10*put;
                put*=10;
            }
            cm/=10;
        }
        if(nrm==0)
        {
            if(max<m)
                max=m;
        }
        else
        {
            t=1;
            s=0;
            while(s+t<=nrm)
            {
              s+=t;
              t+=4;
            }
            if(s==nrm)
            {
              nrcm++;
            }
            if(cnt==0)
            {
              elemm=nrm;
              cnt=1;
            }
        }
    }
    if(p==1)
      out<<max;
    if(p==2)
    {
      if(nrcg>nrcm)
        out<<1;
      if(nrcg<nrcm)
        out<<2;
      if(nrcg==nrcm)
      {
        if(elemm>elemg)
          out<<2;
        if(elemm<elemg)
          out<<1;
        if(elemm==elemg)
          out<<0;
      }
    }
    if(p==3)
    {
      if(nrcg>nrcm)
        out<<nrcg;
      if(nrcg<nrcm)
        out<<nrcm;
      if(nrcg==nrcm)
      {
        if(elemm>elemg)
          out<<elemm;
        if(elemm<elemg)
          out<<elemg;
        if(elemm==elemg)
          out<<0;
      }
    }
        return 0;
    }
